In [44]:
file_Object = open("example.txt", "w")
file_Object.write("assignment 2")
print(f"file created successfully.")
file_Object.close()

file_Object = open("example.txt", "r")
if(file_Object) :
    print("file opened successfully.")
else :
    print("file does not open.")
str = file_Object.read()
print(str)

file created successfully.
file opened successfully.
assignment 2


In [49]:
num_char = int(input("Enter no of character to be read : "))

file_Object = open("example.txt", "r")
str = file_Object.read(num_char)
print(str)

Enter no of character to be read :  5


assig


In [57]:
file_Object = open("example.txt", "a")
file_Object.write("\nAdded line.")
file_Object.close()

file_Object = open("example.txt", "r")
str = file_Object.read()
print(str)
file_Object.close()

assignment 2Added line.Added line.Added line.
Added line.


In [71]:
str = "A girl is playing there badminton.\nThe scenery is beautiful.\nThe birds are flying in the sky.\nThe sky is cloudy.\nAlphabets consists of vowels and consonants."

file_Object = open("example.txt", "w")
file_Object.write(str)
file_Object.close()

def count_lines_not_starting_with_T():
    count = 0
    file_Object = open("example.txt", "r")
    line_str = file_Object.readline()
    
    while len(line_str) != 0:
        if line_str[0] != "T":
            count += 1
        line_str = file_Object.readline()
    
    file_Object.close()
    return count

print(count_lines_not_starting_with_T())


2


In [73]:
file_Object = open("example.txt", "r")
str = file_Object.read()
file_Object.close()

file_Object1 = open("example1.txt", "w")
file_Object1.write(str)
file_Object1.close()

file_Object1 = open("example1.txt", "r")
str = file_Object1.read()
print("written data in new file : ")
print(str)
file_Object1.close()

written data in new file : 
A girl is playing there badminton.
The scenery is beautiful.
The birds are flying in the sky.
The sky is cloudy.
Alphabets consists of vowels and consonants.


In [75]:
import numpy as np

N = int(input("Enter the rows of magrix : "))
M = int(input("Enter the columns of matrix : "))

matrix = []

print("Enter the elements of the matrix:")
for i in range(N):
    row = input().split(" ")
    row1 = []
    for x in row :
        x = int(x)
        row1.append(x)
    matrix.append(row1)

np_matrix = np.array(matrix)

transpose_matrix = np_matrix.T

flattened_matrix = np_matrix.flatten()

print("Transpose of the matrix:")
print(transpose_matrix)

print("Flattened version of the matrix:")
print(flattened_matrix)


Enter the rows of magrix :  2
Enter the columns of matrix :  3


Enter the elements of the matrix:


 1 2 3
 4 5 6


Transpose of the matrix:
[[1 4]
 [2 5]
 [3 6]]
Flattened version of the matrix:
[1 2 3 4 5 6]


In [81]:
import numpy as np

arr1 = np.array([10, 16, 71, 9])
arr2 = np.array([71, 91, 31, 51])

dim1 = arr1.ndim
dim2 = arr2.ndim

print(f"dimension of first array : {dim1}")
print(f"dimension of second array : {dim2}")

shape1 = arr1.shape
shape2 = arr2.shape

print(f"dimension of first array : {shape1}")
print(f"dimension of second array : {shape2}")

size1 = arr1.size
size2 = arr2.size

print(f"dimension of first array : {size1}")
print(f"dimension of second array : {size2}")

dimension of first array : 1
dimension of second array : 1
dimension of first array : (4,)
dimension of second array : (4,)
dimension of first array : 4
dimension of second array : 4


In [117]:
import numpy as np
from numpy import random

arr1 = random.randint(1 ,10, size = (5))
arr2 = random.randint(1, 10, size = (5))

print(f"first array : {arr1}")
print(f"second array : {arr2}")

con_arr = np.concatenate((arr1, arr2))

print(f"concatenate array : {con_arr}")

print(f"sorted first array : {np.sort(arr1)}")
print(f"sorted second array : {np.sort(arr2)}")

add_arr = arr1+arr2
print(f"added array element-wise : {add_arr}")

sub_arr = arr1-arr2
print(f"added array element-wise : {sub_arr}")

mul_arr = arr1 -arr2
print(f"added array element-wise : {mul_arr}")

flag = True
for x in arr2 :
    if x == 0 :
        flag = False
if flag == False :
    print("There is Zero in second array.")
else:
    div_arr = arr1 / arr2
    print(f"added array element-wise : {div_arr}")

first array : [2 7 4 2 6]
second array : [9 1 7 5 9]
concatenate array : [2 7 4 2 6 9 1 7 5 9]
sorted first array : [2 2 4 6 7]
sorted second array : [1 5 7 9 9]
added array element-wise : [11  8 11  7 15]
added array element-wise : [-7  6 -3 -3 -3]
added array element-wise : [-7  6 -3 -3 -3]
added array element-wise : [0.22222222 7.         0.57142857 0.4        0.66666667]


In [123]:
import numpy as np
from numpy import random

matrix = random.randint(1 ,100 , size = (8, 7))

print(matrix)

for i in range (7) :
    maxValue = np.max(matrix[:, i])
    minValue = np.min(matrix[:, i])
    print(f"feature {i+1} : min = {minValue} , max = {maxValue} .")

[[64 47 32  1 11 71 73]
 [65  4 50 27 89 91 30]
 [46 31 60 52 29 15  7]
 [32 81 73  5 72 30 80]
 [61 19 67 74 44 84 19]
 [84 92 42 97 38 58 61]
 [93 89  7 51 91  1 94]
 [16 51 20 15 72 10 52]]
feature 1 : min = 16 , max = 93 .
feature 2 : min = 4 , max = 92 .
feature 3 : min = 7 , max = 73 .
feature 4 : min = 1 , max = 97 .
feature 5 : min = 11 , max = 91 .
feature 6 : min = 1 , max = 91 .
feature 7 : min = 7 , max = 94 .


In [156]:
import numpy as np
from numpy import random

matrix = random.randint(1 ,20 , size = (4, 5))
print("matrix : ")
print(matrix)

arr1 = random.randint(0,1 , size=(10))
print(f"arr1 : {arr1}")
arr2 = random.randint(1,2 , size=(10))
print(f"arr2 : {arr2}")
arr3 = random.randint(5,6 , size=(10))
print(f"arr3 : {arr3}")

even_arr = []
for i in range(10 , 51 , 2) :
    even_arr.append(i)

arr = np.array(even_arr)
print(f"even array : {even_arr}")

print(f"single random number between 0 and 1 : {random.randint(0 , 2)}")

file_Object = open("matrix.txt", "w")
for rows in matrix:
    for element in rows :
        file_Object.write(f"{element} ")
    file_Object.write("\n")
file_Object.close()

matrix : 
[[ 2 10  6 11  1]
 [ 5  8 13 11  8]
 [ 6  7  3  2  4]
 [18  6  1  5  4]]
arr1 : [0 0 0 0 0 0 0 0 0 0]
arr2 : [1 1 1 1 1 1 1 1 1 1]
arr3 : [5 5 5 5 5 5 5 5 5 5]
even array : [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
single random number between 0 and 1 : 1
